### ISSUE TITLE
Fix Fedora 23 Server installs

### ISSUE THREAD

**Issue by sfloess** [FlossWare/cobbler#6]
When attempting a Fedora 23 server install with KOAN, the install fails with:

```
dracut-initqueue[XYZ]: cat: /tmp/dd_disk: No such file or directory
```

**Comment by sfloess** [comment]
Seems to be resolved now.  I was trying:

``` bash
%pre --interpreter /bin/bash
#!/bin/bash

touch /tmp/dd_disk
%end
```

However, as of today, it is working without this.

**Comment by sfloess** [comment]
The problem arose again.  However the failure was more obvious trying F22!

The cobbler import scripts from [FlossWare scripts](https://github.com/FlossWare/scripts) seem to be setting the kernel options to `repo=$tree`.  By removing this in the Cobbler UI, it solves the problem.

Will be fixed permanently when [FlossWare scripts issue 107](https://github.com/FlossWare/scripts/issues/107) is resolved.

**Comment by mlopezcoria** [comment]
I'm trying to install Fedora 23 using the NetInstall image, but I get an error: "/tmp/dd_disk: No such file or directory". I read that I can fix it by applying a couple of patches to Anaconda. I get them from GitHub but I don't know how to apply them. I read it here: https://bugzilla.redhat.com/show_bug.cgi?id=1287870
Thank you in advance

**Comment by sfloess** [comment]
Look at the kernel options for the distro in the web UI.  I believe that a root=$tree gets put in place that causes this issue.

I had posted a similar problem to the Cobbler list and Tom Coote mentioned this bug:  https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1214514

By removing that root=$tree from the kopts, everything fixed itself. 

I saw the Bugzilla link you mentioned as well - and was basically stuck too.  Thankfully, I have scriptified some stuff that I do with cobbler that takes care of ensuring the kopts are set to ''  

Anyway - removing that from the kopts definitely solved my issue and I am able to install Fedora 23 via KOAN.

PS - if you are interested and want to use my scripts, take a look at how I do this for my home network:  https://github.com/sfloess/scripts/blob/master/bash/cobbler.sh

I have my FlossWare scripts as a git submodule for the sfloess git repo...

Let me know if you need any additional help - this one drove me nuts for months.  Somehow along the way I fixed it and then never understood what I did to work around that issue you mention...
